package com.bestnest.domain;

// Generated Dec 6, 2014 5:03:01 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "ozuygqof_bestnest")
public class City implements java.io.Serializable {

	private String cityId;
	private States states;
	private String name;
	private Set<CityLocality> cityLocalities = new HashSet<CityLocality>(0);

	public City() {
	}

	public City(String cityId) {
		this.cityId = cityId;
	}

	public City(String cityId, States states, String name,
			Set<CityLocality> cityLocalities) {
		this.cityId = cityId;
		this.states = states;
		this.name = name;
		this.cityLocalities = cityLocalities;
	}

	@Id
	@Column(name = "city_id", unique = true, nullable = false, length = 10)
	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "state_id")
	public States getStates() {
		return this.states;
	}

	public void setStates(States states) {
		this.states = states;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<CityLocality> getCityLocalities() {
		return this.cityLocalities;
	}

	public void setCityLocalities(Set<CityLocality> cityLocalities) {
		this.cityLocalities = cityLocalities;
	}

}
