package com.bestnest.domain;

// Generated Dec 6, 2014 5:03:01 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CityLocality generated by hbm2java
 */
@Entity
@Table(name = "city_locality", catalog = "ozuygqof_bestnest")
public class CityLocality implements java.io.Serializable {

	private Integer cityLocalityId;
	private City city;
	private String locality;
	private Set<Address> addresses = new HashSet<Address>(0);

	public CityLocality() {
	}

	public CityLocality(City city, String locality, Set<Address> addresses) {
		this.city = city;
		this.locality = locality;
		this.addresses = addresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "city_locality_id", unique = true, nullable = false)
	public Integer getCityLocalityId() {
		return this.cityLocalityId;
	}

	public void setCityLocalityId(Integer cityLocalityId) {
		this.cityLocalityId = cityLocalityId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "city_id")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "locality", length = 45)
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "cityLocality")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
