package com.bestnest.domain;

// Generated Dec 6, 2014 5:03:01 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LocalityInfo generated by hbm2java
 */
@Entity
@Table(name = "locality_info", catalog = "ozuygqof_bestnest")
public class LocalityInfo implements java.io.Serializable {

	private Integer localityInfoId;
	private String busStop;
	private String metroTrain;
	private String schools;
	private String shoppingMall;
	private String hospitals;
	private String banksAtm;
	private String worship;
	private String groceryStores;
	private String pharmacy;
	private String restaurent;
	private String park;
	private String movies;
	private String gym;
	private String airport;
	private Set<Project> projects = new HashSet<Project>(0);

	public LocalityInfo() {
	}

	public LocalityInfo(String busStop, String metroTrain, String schools,
			String shoppingMall, String hospitals, String banksAtm,
			String worship, String groceryStores, String pharmacy,
			String restaurent, String park, String movies, String gym,
			String airport, Set<Project> projects) {
		this.busStop = busStop;
		this.metroTrain = metroTrain;
		this.schools = schools;
		this.shoppingMall = shoppingMall;
		this.hospitals = hospitals;
		this.banksAtm = banksAtm;
		this.worship = worship;
		this.groceryStores = groceryStores;
		this.pharmacy = pharmacy;
		this.restaurent = restaurent;
		this.park = park;
		this.movies = movies;
		this.gym = gym;
		this.airport = airport;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "locality_info_id", unique = true, nullable = false)
	public Integer getLocalityInfoId() {
		return this.localityInfoId;
	}

	public void setLocalityInfoId(Integer localityInfoId) {
		this.localityInfoId = localityInfoId;
	}

	@Column(name = "bus_stop", length = 45)
	public String getBusStop() {
		return this.busStop;
	}

	public void setBusStop(String busStop) {
		this.busStop = busStop;
	}

	@Column(name = "metro_train", length = 45)
	public String getMetroTrain() {
		return this.metroTrain;
	}

	public void setMetroTrain(String metroTrain) {
		this.metroTrain = metroTrain;
	}

	@Column(name = "schools", length = 45)
	public String getSchools() {
		return this.schools;
	}

	public void setSchools(String schools) {
		this.schools = schools;
	}

	@Column(name = "shopping_mall", length = 45)
	public String getShoppingMall() {
		return this.shoppingMall;
	}

	public void setShoppingMall(String shoppingMall) {
		this.shoppingMall = shoppingMall;
	}

	@Column(name = "hospitals", length = 45)
	public String getHospitals() {
		return this.hospitals;
	}

	public void setHospitals(String hospitals) {
		this.hospitals = hospitals;
	}

	@Column(name = "banks_atm", length = 45)
	public String getBanksAtm() {
		return this.banksAtm;
	}

	public void setBanksAtm(String banksAtm) {
		this.banksAtm = banksAtm;
	}

	@Column(name = "worship", length = 45)
	public String getWorship() {
		return this.worship;
	}

	public void setWorship(String worship) {
		this.worship = worship;
	}

	@Column(name = "grocery_stores", length = 45)
	public String getGroceryStores() {
		return this.groceryStores;
	}

	public void setGroceryStores(String groceryStores) {
		this.groceryStores = groceryStores;
	}

	@Column(name = "pharmacy", length = 45)
	public String getPharmacy() {
		return this.pharmacy;
	}

	public void setPharmacy(String pharmacy) {
		this.pharmacy = pharmacy;
	}

	@Column(name = "restaurent", length = 45)
	public String getRestaurent() {
		return this.restaurent;
	}

	public void setRestaurent(String restaurent) {
		this.restaurent = restaurent;
	}

	@Column(name = "park", length = 45)
	public String getPark() {
		return this.park;
	}

	public void setPark(String park) {
		this.park = park;
	}

	@Column(name = "movies", length = 45)
	public String getMovies() {
		return this.movies;
	}

	public void setMovies(String movies) {
		this.movies = movies;
	}

	@Column(name = "gym", length = 45)
	public String getGym() {
		return this.gym;
	}

	public void setGym(String gym) {
		this.gym = gym;
	}

	@Column(name = "airport", length = 45)
	public String getAirport() {
		return this.airport;
	}

	public void setAirport(String airport) {
		this.airport = airport;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "localityInfo")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
