package com.bestnest.domain;

// Generated Feb 27, 2015 5:30:32 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProjectImage generated by hbm2java
 */
@Entity
@Table(name = "project_image", catalog = "ozuygqof_bestnest")
public class ProjectImage implements java.io.Serializable {

	private Integer projectImageId;
	private String floorPlan;
	private String locationMap;
	private String sitePlan;
	private String priceDetail;
	private String specification;
	private String slideImages;
	private String googleMap;
	private String googleMapLatlang;
	private Set<ProjectDetails> projectDetailses = new HashSet<ProjectDetails>(
			0);

	public ProjectImage() {
	}

	public ProjectImage(String floorPlan, String locationMap, String sitePlan,
			String priceDetail, String specification, String slideImages,
			String googleMap, String googleMapLatlang,
			Set<ProjectDetails> projectDetailses) {
		this.floorPlan = floorPlan;
		this.locationMap = locationMap;
		this.sitePlan = sitePlan;
		this.priceDetail = priceDetail;
		this.specification = specification;
		this.slideImages = slideImages;
		this.googleMap = googleMap;
		this.googleMapLatlang = googleMapLatlang;
		this.projectDetailses = projectDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_image_id", unique = true, nullable = false)
	public Integer getProjectImageId() {
		return this.projectImageId;
	}

	public void setProjectImageId(Integer projectImageId) {
		this.projectImageId = projectImageId;
	}

	@Column(name = "floor_plan", length = 1000)
	public String getFloorPlan() {
		return this.floorPlan;
	}

	public void setFloorPlan(String floorPlan) {
		this.floorPlan = floorPlan;
	}

	@Column(name = "location_map", length = 100)
	public String getLocationMap() {
		return this.locationMap;
	}

	public void setLocationMap(String locationMap) {
		this.locationMap = locationMap;
	}

	@Column(name = "site_plan", length = 100)
	public String getSitePlan() {
		return this.sitePlan;
	}

	public void setSitePlan(String sitePlan) {
		this.sitePlan = sitePlan;
	}

	@Column(name = "price_detail", length = 1000)
	public String getPriceDetail() {
		return this.priceDetail;
	}

	public void setPriceDetail(String priceDetail) {
		this.priceDetail = priceDetail;
	}

	@Column(name = "specification", length = 100)
	public String getSpecification() {
		return this.specification;
	}

	public void setSpecification(String specification) {
		this.specification = specification;
	}

	@Column(name = "slide_images", length = 1000)
	public String getSlideImages() {
		return this.slideImages;
	}

	public void setSlideImages(String slideImages) {
		this.slideImages = slideImages;
	}

	@Column(name = "google_map", length = 500)
	public String getGoogleMap() {
		return this.googleMap;
	}

	public void setGoogleMap(String googleMap) {
		this.googleMap = googleMap;
	}

	@Column(name = "google_map_latlang", length = 100)
	public String getGoogleMapLatlang() {
		return this.googleMapLatlang;
	}

	public void setGoogleMapLatlang(String googleMapLatlang) {
		this.googleMapLatlang = googleMapLatlang;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "projectImage")
	public Set<ProjectDetails> getProjectDetailses() {
		return this.projectDetailses;
	}

	public void setProjectDetailses(Set<ProjectDetails> projectDetailses) {
		this.projectDetailses = projectDetailses;
	}

}
