package com.bestnest.domain;

// Generated Feb 18, 2015 10:55:05 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * ProjectSimilar generated by hbm2java
 */
@Entity
@Table(name = "project_similar", catalog = "ozuygqof_bestnest")
@NamedQuery(name = "ProjectSimilar.findProjectSimilarByProjectId", query = "select p from ProjectSimilar p where p.projectByProjectId = ?1")
public class ProjectSimilar implements java.io.Serializable {

	private int projectSimilarId;
	private Project projectByProjectSimilarMappingId;
	private Project projectByProjectId;

	public ProjectSimilar() {
	}

	public ProjectSimilar(int projectSimilarId) {
		this.projectSimilarId = projectSimilarId;
	}

	public ProjectSimilar(int projectSimilarId,
			Project projectByProjectSimilarMappingId, Project projectByProjectId) {
		this.projectSimilarId = projectSimilarId;
		this.projectByProjectSimilarMappingId = projectByProjectSimilarMappingId;
		this.projectByProjectId = projectByProjectId;
	}

	@Id
	@Column(name = "project_similar_id", unique = true, nullable = false)
	public int getProjectSimilarId() {
		return this.projectSimilarId;
	}

	public void setProjectSimilarId(int projectSimilarId) {
		this.projectSimilarId = projectSimilarId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_similar_mapping_id")
	public Project getProjectByProjectSimilarMappingId() {
		return this.projectByProjectSimilarMappingId;
	}

	public void setProjectByProjectSimilarMappingId(
			Project projectByProjectSimilarMappingId) {
		this.projectByProjectSimilarMappingId = projectByProjectSimilarMappingId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public Project getProjectByProjectId() {
		return this.projectByProjectId;
	}

	public void setProjectByProjectId(Project projectByProjectId) {
		this.projectByProjectId = projectByProjectId;
	}
	

}
