package com.bestnest.domain;

// Generated Feb 22, 2015 7:27:35 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectPrice generated by hbm2java
 */
@Entity
@Table(name = "project_price", catalog = "ozuygqof_bestnest")
public class ProjectPrice implements java.io.Serializable {

	private Integer projectPriceId;
	private ProjectDetails projectDetails;
	private String paymentPlan;
	private BigDecimal companyRate;
	private String companyDiscount;
	private String brokerDiscount;
	private String maxCustomerDiscountFromBrokerDiscount;
	private String companyOtherBenifit;
	private String companyOtherBenifit2;

	public ProjectPrice() {
	}

	public ProjectPrice(ProjectDetails projectDetails, String paymentPlan,
			BigDecimal companyRate, String companyDiscount,
			String brokerDiscount,
			String maxCustomerDiscountFromBrokerDiscount,
			String companyOtherBenifit, String companyOtherBenifit2) {
		this.projectDetails = projectDetails;
		this.paymentPlan = paymentPlan;
		this.companyRate = companyRate;
		this.companyDiscount = companyDiscount;
		this.brokerDiscount = brokerDiscount;
		this.maxCustomerDiscountFromBrokerDiscount = maxCustomerDiscountFromBrokerDiscount;
		this.companyOtherBenifit = companyOtherBenifit;
		this.companyOtherBenifit2 = companyOtherBenifit2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_price_id", unique = true, nullable = false)
	public Integer getProjectPriceId() {
		return this.projectPriceId;
	}

	public void setProjectPriceId(Integer projectPriceId) {
		this.projectPriceId = projectPriceId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_details_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@Column(name = "payment_plan", length = 45)
	public String getPaymentPlan() {
		return this.paymentPlan;
	}

	public void setPaymentPlan(String paymentPlan) {
		this.paymentPlan = paymentPlan;
	}

	@Column(name = "company_rate", precision = 9)
	public BigDecimal getCompanyRate() {
		return this.companyRate;
	}

	public void setCompanyRate(BigDecimal companyRate) {
		this.companyRate = companyRate;
	}

	@Column(name = "company_discount", length = 25)
	public String getCompanyDiscount() {
		return this.companyDiscount;
	}

	public void setCompanyDiscount(String companyDiscount) {
		this.companyDiscount = companyDiscount;
	}

	@Column(name = "broker_discount", length = 45)
	public String getBrokerDiscount() {
		return this.brokerDiscount;
	}

	public void setBrokerDiscount(String brokerDiscount) {
		this.brokerDiscount = brokerDiscount;
	}

	@Column(name = "max_customer_discount_from_broker_discount", length = 45)
	public String getMaxCustomerDiscountFromBrokerDiscount() {
		return this.maxCustomerDiscountFromBrokerDiscount;
	}

	public void setMaxCustomerDiscountFromBrokerDiscount(
			String maxCustomerDiscountFromBrokerDiscount) {
		this.maxCustomerDiscountFromBrokerDiscount = maxCustomerDiscountFromBrokerDiscount;
	}

	@Column(name = "company_other_benifit", length = 45)
	public String getCompanyOtherBenifit() {
		return this.companyOtherBenifit;
	}

	public void setCompanyOtherBenifit(String companyOtherBenifit) {
		this.companyOtherBenifit = companyOtherBenifit;
	}

	@Column(name = "company_other_benifit_2", length = 45)
	public String getCompanyOtherBenifit2() {
		return this.companyOtherBenifit2;
	}

	public void setCompanyOtherBenifit2(String companyOtherBenifit2) {
		this.companyOtherBenifit2 = companyOtherBenifit2;
	}

}
