package com.bestnest.domain;

// Generated Dec 6, 2014 5:03:01 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Purpose generated by hbm2java
 */
@Entity
@Table(name = "purpose", catalog = "ozuygqof_bestnest")
public class Purpose implements java.io.Serializable {

	private String purposeId;
	private Set<ProjectDetails> projectDetailses = new HashSet<ProjectDetails>(
			0);

	public Purpose() {
	}

	public Purpose(String purposeId) {
		this.purposeId = purposeId;
	}

	public Purpose(String purposeId, Set<ProjectDetails> projectDetailses) {
		this.purposeId = purposeId;
		this.projectDetailses = projectDetailses;
	}

	@Id
	@Column(name = "purpose_id", unique = true, nullable = false, length = 50)
	public String getPurposeId() {
		return this.purposeId;
	}

	public void setPurposeId(String purposeId) {
		this.purposeId = purposeId;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "purpose")
	public Set<ProjectDetails> getProjectDetailses() {
		return this.projectDetailses;
	}

	public void setProjectDetailses(Set<ProjectDetails> projectDetailses) {
		this.projectDetailses = projectDetailses;
	}

}
