package com.bestnest.domain;

// Generated Dec 23, 2014 3:18:52 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesRegister generated by hbm2java
 */
@Entity
@Table(name = "sales_register", catalog = "ozuygqof_bestnest")
public class SalesRegister implements java.io.Serializable {

	private Integer salesRegisterId;
	private ClientInformation clientInformation;
	private UserProfile userProfileByUserProfileId;
	private ProjectDetails projectDetails;
	private UserProfile userProfileByAssociatesRmId;
	private UserProfile userProfileByMentorCreditNoteId;
	private UserProfile userProfileByTcReRpId;
	private String paymentPlan;
	private String unitTypeNoTower;
	private BigDecimal companyRatePerSqFtAfterDiscount;
	private BigDecimal actualRatePerSqFt;
	private String channelPartner;
	private BigDecimal tcReRpFee;
	private BigDecimal associatesRmFee;
	private BigDecimal mentorCreditNoteFee;
	private BigDecimal commssionSlabsFromCompanyPrcnt;
	private BigDecimal commssionSlabsFromCompany;
	private BigDecimal otherBenifitFromCompany;
	private BigDecimal discountGivenFromCommission;
	private BigDecimal discountGivenFromOtherBenefits;
	private BigDecimal commissionToBestnest;
	private BigDecimal otherBenefitsToBestnest;
	private BigDecimal netCommissionToBestnest;
	private Date bookingDate;

	public SalesRegister() {
	}

	public SalesRegister(ClientInformation clientInformation,
			UserProfile userProfileByUserProfileId,
			ProjectDetails projectDetails,
			UserProfile userProfileByAssociatesRmId,
			UserProfile userProfileByMentorCreditNoteId,
			UserProfile userProfileByTcReRpId, String paymentPlan,
			String unitTypeNoTower, BigDecimal companyRatePerSqFtAfterDiscount,
			BigDecimal actualRatePerSqFt, String channelPartner,
			BigDecimal tcReRpFee, BigDecimal associatesRmFee,
			BigDecimal mentorCreditNoteFee,
			BigDecimal commssionSlabsFromCompanyPrcnt,
			BigDecimal commssionSlabsFromCompany,
			BigDecimal otherBenifitFromCompany,
			BigDecimal discountGivenFromCommission,
			BigDecimal discountGivenFromOtherBenefits,
			BigDecimal commissionToBestnest,
			BigDecimal otherBenefitsToBestnest,
			BigDecimal netCommissionToBestnest, Date bookingDate) {
		this.clientInformation = clientInformation;
		this.userProfileByUserProfileId = userProfileByUserProfileId;
		this.projectDetails = projectDetails;
		this.userProfileByAssociatesRmId = userProfileByAssociatesRmId;
		this.userProfileByMentorCreditNoteId = userProfileByMentorCreditNoteId;
		this.userProfileByTcReRpId = userProfileByTcReRpId;
		this.paymentPlan = paymentPlan;
		this.unitTypeNoTower = unitTypeNoTower;
		this.companyRatePerSqFtAfterDiscount = companyRatePerSqFtAfterDiscount;
		this.actualRatePerSqFt = actualRatePerSqFt;
		this.channelPartner = channelPartner;
		this.tcReRpFee = tcReRpFee;
		this.associatesRmFee = associatesRmFee;
		this.mentorCreditNoteFee = mentorCreditNoteFee;
		this.commssionSlabsFromCompanyPrcnt = commssionSlabsFromCompanyPrcnt;
		this.commssionSlabsFromCompany = commssionSlabsFromCompany;
		this.otherBenifitFromCompany = otherBenifitFromCompany;
		this.discountGivenFromCommission = discountGivenFromCommission;
		this.discountGivenFromOtherBenefits = discountGivenFromOtherBenefits;
		this.commissionToBestnest = commissionToBestnest;
		this.otherBenefitsToBestnest = otherBenefitsToBestnest;
		this.netCommissionToBestnest = netCommissionToBestnest;
		this.bookingDate = bookingDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sales_register_id", unique = true, nullable = false)
	public Integer getSalesRegisterId() {
		return this.salesRegisterId;
	}

	public void setSalesRegisterId(Integer salesRegisterId) {
		this.salesRegisterId = salesRegisterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_information_id")
	public ClientInformation getClientInformation() {
		return this.clientInformation;
	}

	public void setClientInformation(ClientInformation clientInformation) {
		this.clientInformation = clientInformation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_profile_id")
	public UserProfile getUserProfileByUserProfileId() {
		return this.userProfileByUserProfileId;
	}

	public void setUserProfileByUserProfileId(
			UserProfile userProfileByUserProfileId) {
		this.userProfileByUserProfileId = userProfileByUserProfileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_details_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "associates_rm_id")
	public UserProfile getUserProfileByAssociatesRmId() {
		return this.userProfileByAssociatesRmId;
	}

	public void setUserProfileByAssociatesRmId(
			UserProfile userProfileByAssociatesRmId) {
		this.userProfileByAssociatesRmId = userProfileByAssociatesRmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mentor_credit_note_id")
	public UserProfile getUserProfileByMentorCreditNoteId() {
		return this.userProfileByMentorCreditNoteId;
	}

	public void setUserProfileByMentorCreditNoteId(
			UserProfile userProfileByMentorCreditNoteId) {
		this.userProfileByMentorCreditNoteId = userProfileByMentorCreditNoteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tc_re_rp_id")
	public UserProfile getUserProfileByTcReRpId() {
		return this.userProfileByTcReRpId;
	}

	public void setUserProfileByTcReRpId(UserProfile userProfileByTcReRpId) {
		this.userProfileByTcReRpId = userProfileByTcReRpId;
	}

	@Column(name = "payment_plan", length = 45)
	public String getPaymentPlan() {
		return this.paymentPlan;
	}

	public void setPaymentPlan(String paymentPlan) {
		this.paymentPlan = paymentPlan;
	}

	@Column(name = "unit_type_no_tower", length = 100)
	public String getUnitTypeNoTower() {
		return this.unitTypeNoTower;
	}

	public void setUnitTypeNoTower(String unitTypeNoTower) {
		this.unitTypeNoTower = unitTypeNoTower;
	}

	@Column(name = "company_rate_per_sq_ft_after_discount", precision = 9)
	public BigDecimal getCompanyRatePerSqFtAfterDiscount() {
		return this.companyRatePerSqFtAfterDiscount;
	}

	public void setCompanyRatePerSqFtAfterDiscount(
			BigDecimal companyRatePerSqFtAfterDiscount) {
		this.companyRatePerSqFtAfterDiscount = companyRatePerSqFtAfterDiscount;
	}

	@Column(name = "actual_rate_per_sq_ft", precision = 9)
	public BigDecimal getActualRatePerSqFt() {
		return this.actualRatePerSqFt;
	}

	public void setActualRatePerSqFt(BigDecimal actualRatePerSqFt) {
		this.actualRatePerSqFt = actualRatePerSqFt;
	}

	@Column(name = "channel_partner", length = 45)
	public String getChannelPartner() {
		return this.channelPartner;
	}

	public void setChannelPartner(String channelPartner) {
		this.channelPartner = channelPartner;
	}

	@Column(name = "tc_re_rp_fee", precision = 9)
	public BigDecimal getTcReRpFee() {
		return this.tcReRpFee;
	}

	public void setTcReRpFee(BigDecimal tcReRpFee) {
		this.tcReRpFee = tcReRpFee;
	}

	@Column(name = "associates_rm_fee", precision = 9)
	public BigDecimal getAssociatesRmFee() {
		return this.associatesRmFee;
	}

	public void setAssociatesRmFee(BigDecimal associatesRmFee) {
		this.associatesRmFee = associatesRmFee;
	}

	@Column(name = "mentor_credit_note_fee", precision = 9)
	public BigDecimal getMentorCreditNoteFee() {
		return this.mentorCreditNoteFee;
	}

	public void setMentorCreditNoteFee(BigDecimal mentorCreditNoteFee) {
		this.mentorCreditNoteFee = mentorCreditNoteFee;
	}

	@Column(name = "commssion_slabs_from_company_prcnt", precision = 9)
	public BigDecimal getCommssionSlabsFromCompanyPrcnt() {
		return this.commssionSlabsFromCompanyPrcnt;
	}

	public void setCommssionSlabsFromCompanyPrcnt(
			BigDecimal commssionSlabsFromCompanyPrcnt) {
		this.commssionSlabsFromCompanyPrcnt = commssionSlabsFromCompanyPrcnt;
	}

	@Column(name = "commssion_slabs_from_company", precision = 9)
	public BigDecimal getCommssionSlabsFromCompany() {
		return this.commssionSlabsFromCompany;
	}

	public void setCommssionSlabsFromCompany(
			BigDecimal commssionSlabsFromCompany) {
		this.commssionSlabsFromCompany = commssionSlabsFromCompany;
	}

	@Column(name = "other_benifit_from_company", precision = 9)
	public BigDecimal getOtherBenifitFromCompany() {
		return this.otherBenifitFromCompany;
	}

	public void setOtherBenifitFromCompany(BigDecimal otherBenifitFromCompany) {
		this.otherBenifitFromCompany = otherBenifitFromCompany;
	}

	@Column(name = "discount_given_from_commission", precision = 9)
	public BigDecimal getDiscountGivenFromCommission() {
		return this.discountGivenFromCommission;
	}

	public void setDiscountGivenFromCommission(
			BigDecimal discountGivenFromCommission) {
		this.discountGivenFromCommission = discountGivenFromCommission;
	}

	@Column(name = "discount_given_from_other_benefits", precision = 9)
	public BigDecimal getDiscountGivenFromOtherBenefits() {
		return this.discountGivenFromOtherBenefits;
	}

	public void setDiscountGivenFromOtherBenefits(
			BigDecimal discountGivenFromOtherBenefits) {
		this.discountGivenFromOtherBenefits = discountGivenFromOtherBenefits;
	}

	@Column(name = "commission_to_bestnest", precision = 9)
	public BigDecimal getCommissionToBestnest() {
		return this.commissionToBestnest;
	}

	public void setCommissionToBestnest(BigDecimal commissionToBestnest) {
		this.commissionToBestnest = commissionToBestnest;
	}

	@Column(name = "other_benefits_to_bestnest", precision = 9)
	public BigDecimal getOtherBenefitsToBestnest() {
		return this.otherBenefitsToBestnest;
	}

	public void setOtherBenefitsToBestnest(BigDecimal otherBenefitsToBestnest) {
		this.otherBenefitsToBestnest = otherBenefitsToBestnest;
	}

	@Column(name = "net_commission_to_bestnest", precision = 9)
	public BigDecimal getNetCommissionToBestnest() {
		return this.netCommissionToBestnest;
	}

	public void setNetCommissionToBestnest(BigDecimal netCommissionToBestnest) {
		this.netCommissionToBestnest = netCommissionToBestnest;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "booking_date", length = 19)
	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

}
