package com.bestnest.domain;

// Generated Dec 6, 2014 5:03:01 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * States generated by hbm2java
 */
@Entity
@Table(name = "states", catalog = "ozuygqof_bestnest")
public class States implements java.io.Serializable {

	private String stateId;
	private String name;
	private Set<City> cities = new HashSet<City>(0);

	public States() {
	}

	public States(String stateId) {
		this.stateId = stateId;
	}

	public States(String stateId, String name, Set<City> cities) {
		this.stateId = stateId;
		this.name = name;
		this.cities = cities;
	}

	@Id
	@Column(name = "state_id", unique = true, nullable = false, length = 45)
	public String getStateId() {
		return this.stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "states")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
